### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by Ajax07** [bgin/Guided-Missile-Modeling-Simulation#1]
Hi sir 

This project not have cmake how can we build this project also not having main function to compile this code

**Comment by bgin** [comment]
Hello,
This project is not finished yet.
The project repository is serving as a back up now.
You can use (if you wish) some standalone files mainly those belonging to math and radiolocation folders.
You will need Fortran compiler also.

Stay tuned for more updates.

**Comment by bgin** [comment]
I'm closing this issue as it is resolved.
